# Generated by Django 5.0.3 on 2024-03-25 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pekerjaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pekerjaan', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'pekerjaan',
                'ordering': ('pekerjaan',),
            },
        ),
        migrations.CreateModel(
            name='Pelaksana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelaksana', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'pelaksana',
                'ordering': ('pelaksana',),
            },
        ),
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pengguna', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'pengguna',
                'ordering': ('pengguna',),
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'status',
                'ordering': ('status',),
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jam', models.DateField()),
                ('keterangan', models.CharField(max_length=255)),
                ('jenis_pekerjaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pekerjaan')),
                ('pelaksana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pelaksana')),
                ('pengguna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pengguna')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.status')),
            ],
        ),
    ]
