# Generated by Django 5.0.3 on 2024-04-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['jam']},
        ),
        migrations.AlterField(
            model_name='report',
            name='keterangan',
            field=models.TextField(),
        ),
    ]
