# Generated by Django 5.0.3 on 2024-04-02 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_report_options_alter_report_keterangan'),
    ]

    operations = [
    ]
