# Generated by Django 5.0.3 on 2024-04-02 01:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20240402_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='tanggal',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='jam',
            field=models.TimeField(),
        ),
    ]
