# Generated by Django 5.0.3 on 2024-04-02 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_report_tanggal_alter_report_jam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['tanggal', 'jam']},
        ),
    ]
