# Generated by Django 5.0.3 on 2024-04-02 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_report_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='pengguna',
            new_name='user',
        ),
    ]
