# Generated by Django 5.0.3 on 2024-04-04 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_pengguna_report_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-tanggal', '-jam']},
        ),
    ]
