# Generated by Django 5.0.3 on 2024-03-18 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pekerjaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pekerjaan', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('pekerjaan',),
            },
        ),
        migrations.CreateModel(
            name='Pelaksana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelaksana', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('pelaksana',),
            },
        ),
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pengguna', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('pengguna',),
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('status',),
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.IntegerField(default=0)),
                ('jam', models.DateTimeField(auto_now_add=True)),
                ('Keterangan', models.CharField(max_length=255)),
                ('jenis_pekerjaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.pekerjaan')),
                ('pelaksana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.pelaksana')),
                ('pengguna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.pengguna')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.status')),
            ],
        ),
    ]
