# Generated by Django 5.0.3 on 2024-03-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pekerjaan',
            options={'ordering': ('pekerjaan',), 'verbose_name_plural': 'pekerjaan'},
        ),
        migrations.AlterModelOptions(
            name='pelaksana',
            options={'ordering': ('pelaksana',), 'verbose_name_plural': 'pelaksana'},
        ),
        migrations.AlterModelOptions(
            name='pengguna',
            options={'ordering': ('pengguna',), 'verbose_name_plural': 'pengguna'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ('status',), 'verbose_name_plural': 'status'},
        ),
        migrations.RenameField(
            model_name='report',
            old_name='Keterangan',
            new_name='keterangan',
        ),
        migrations.RemoveField(
            model_name='report',
            name='nomor',
        ),
        migrations.AlterField(
            model_name='report',
            name='jam',
            field=models.DateField(),
        ),
    ]
